DEMO_INTENTS = [
    {
        "id": "intent_demo_fog_blue_cotton",
        "raw_text": "客户要高级一点的雾霾蓝，别太紫，做在棉针织上。",
        "intent_type": "方案生成",
        "fabric": "纯棉针织汗布",
        "color_name": "雾霾蓝",
        "target_lab": {"l": 62.4, "a": -3.1, "b": -11.8},
        "dye_type": "活性染料",
        "confidence": 0.88,
    },
    {
        "id": "intent_demo_polyester_black",
        "raw_text": "涤纶四面弹要做一个稳定黑色，看下历史配方。",
        "intent_type": "历史查询",
        "fabric": "涤纶四面弹",
        "color_name": "黑色",
        "target_lab": {"l": 15.8, "a": 0.4, "b": -1.5},
        "dye_type": "分散染料",
        "confidence": 0.91,
    },
    {
        "id": "intent_demo_nylon_purple",
        "raw_text": "锦纶塔丝隆深紫色上次偏深，这次怎么调安全？",
        "intent_type": "模拟调参",
        "fabric": "锦纶塔丝隆",
        "color_name": "深紫",
        "target_lab": {"l": 30.5, "a": 35.0, "b": -30.0},
        "dye_type": "酸性染料",
        "confidence": 0.86,
    },
    {
        "id": "intent_demo_acrylic_royal_blue",
        "raw_text": "腈纶围巾宝蓝要减少色花风险，找类似历史订单。",
        "intent_type": "风险预警",
        "fabric": "腈纶围巾",
        "color_name": "宝蓝",
        "target_lab": {"l": 30.0, "a": 8.0, "b": -42.0},
        "dye_type": "阳离子染料",
        "confidence": 0.84,
    },
]

HISTORICAL_BATCHES = [
    {
        "id": "hist_cotton_fog_blue_001",
        "batch_no": "HB-COT-20260512-001",
        "fabric": "纯棉针织汗布",
        "fiber_composition": "95%棉 + 5%氨纶",
        "fabric_weight_gsm": 180,
        "color_name": "雾霾蓝",
        "target_lab": {"l": 62.4, "a": -3.1, "b": -11.8},
        "actual_lab": {"l": 62.1, "a": -2.9, "b": -12.0},
        "delta_e": 0.6,
        "rft": True,
        "reworked": False,
        "dye_type": "活性染料",
        "dye_formula": [
            {"name": "活性蓝 B-19", "dosage": 1.18, "unit": "% o.w.f."},
            {"name": "活性红 3BS", "dosage": 0.32, "unit": "% o.w.f."},
            {"name": "活性黄 3RS", "dosage": 0.08, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 60,
            "pH": 10.6,
            "liquor_ratio": 8,
            "salt": 60,
            "alkali": 20,
            "hold_time": 45,
            "heating_rate": 1.5,
        },
        "machine_id": "MACHINE_03",
        "result_note": "稳定一次成功批次，可作为雾蓝主参考。",
    },
    {
        "id": "hist_cotton_fog_blue_002",
        "batch_no": "HB-COT-20260618-002",
        "fabric": "纯棉针织汗布",
        "fiber_composition": "95%棉 + 5%氨纶",
        "fabric_weight_gsm": 185,
        "color_name": "雾霾蓝",
        "target_lab": {"l": 62.4, "a": -3.1, "b": -11.8},
        "actual_lab": {"l": 60.8, "a": -1.7, "b": -13.5},
        "delta_e": 2.2,
        "rft": False,
        "reworked": True,
        "dye_type": "活性染料",
        "dye_formula": [
            {"name": "活性蓝 B-19", "dosage": 1.28, "unit": "% o.w.f."},
            {"name": "活性红 3BS", "dosage": 0.38, "unit": "% o.w.f."},
            {"name": "活性黄 3RS", "dosage": 0.10, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 64,
            "pH": 10.9,
            "liquor_ratio": 8,
            "salt": 68,
            "alkali": 22,
            "hold_time": 50,
            "heating_rate": 1.8,
        },
        "machine_id": "MACHINE_08",
        "result_note": "首次偏深偏蓝，回修后通过；温度和主染料偏高。",
    },
    {
        "id": "hist_cotton_sky_blue_001",
        "batch_no": "HB-COT-20260421-003",
        "fabric": "纯棉梭织府绸",
        "fiber_composition": "100%棉",
        "fabric_weight_gsm": 120,
        "color_name": "天空蓝",
        "target_lab": {"l": 70.8, "a": -5.2, "b": -18.6},
        "actual_lab": {"l": 71.1, "a": -5.0, "b": -18.2},
        "delta_e": 0.7,
        "rft": True,
        "reworked": False,
        "dye_type": "活性染料",
        "dye_formula": [
            {"name": "活性蓝 B-19", "dosage": 0.62, "unit": "% o.w.f."},
            {"name": "活性黄 3RS", "dosage": 0.04, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 60,
            "pH": 10.5,
            "liquor_ratio": 10,
            "salt": 45,
            "alkali": 16,
            "hold_time": 40,
            "heating_rate": 1.5,
        },
        "machine_id": "MACHINE_02",
        "result_note": "浅蓝批次，盐碱低于中深色。",
    },
    {
        "id": "hist_polyester_black_001",
        "batch_no": "HB-PET-20260218-002",
        "fabric": "涤纶四面弹",
        "fiber_composition": "92%涤纶 + 8%氨纶",
        "fabric_weight_gsm": 180,
        "color_name": "黑色",
        "target_lab": {"l": 15.8, "a": 0.4, "b": -1.5},
        "actual_lab": {"l": 16.6, "a": 0.2, "b": -1.0},
        "delta_e": 1.0,
        "rft": True,
        "reworked": False,
        "dye_type": "分散染料",
        "dye_formula": [
            {"name": "分散黑 ECO", "dosage": 4.80, "unit": "% o.w.f."},
            {"name": "分散蓝 2BLN", "dosage": 0.35, "unit": "% o.w.f."},
            {"name": "分散红玉 S-5BL", "dosage": 0.20, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 130,
            "pH": 5.0,
            "liquor_ratio": 10,
            "dispersant": 1.2,
            "leveling_agent": 0.6,
            "hold_time": 60,
            "heating_rate": 1.2,
        },
        "machine_id": "MACHINE_12",
        "result_note": "氨纶混纺黑色，温度不能过高。",
    },
    {
        "id": "hist_polyester_royal_blue_001",
        "batch_no": "HB-PET-20260316-001",
        "fabric": "涤纶春亚纺",
        "fiber_composition": "100%涤纶",
        "fabric_weight_gsm": 95,
        "color_name": "宝蓝",
        "target_lab": {"l": 31.2, "a": 4.0, "b": -39.5},
        "actual_lab": {"l": 31.0, "a": 4.3, "b": -39.0},
        "delta_e": 0.6,
        "rft": True,
        "reworked": False,
        "dye_type": "分散染料",
        "dye_formula": [
            {"name": "分散蓝 2BLN", "dosage": 1.85, "unit": "% o.w.f."},
            {"name": "分散紫 HFRL", "dosage": 0.10, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 130,
            "pH": 5.0,
            "liquor_ratio": 10,
            "dispersant": 1.0,
            "leveling_agent": 0.5,
            "hold_time": 45,
            "heating_rate": 1.5,
        },
        "machine_id": "MACHINE_11",
        "result_note": "涤纶宝蓝标准批次。",
    },
    {
        "id": "hist_polyester_ink_green_001",
        "batch_no": "HB-PET-20260602-005",
        "fabric": "涤纶桃皮绒",
        "fiber_composition": "100%涤纶",
        "fabric_weight_gsm": 150,
        "color_name": "墨绿",
        "target_lab": {"l": 28.0, "a": -19.0, "b": 9.5},
        "actual_lab": {"l": 26.5, "a": -20.8, "b": 8.7},
        "delta_e": 2.2,
        "rft": False,
        "reworked": True,
        "dye_type": "分散染料",
        "dye_formula": [
            {"name": "分散蓝 2BLN", "dosage": 1.55, "unit": "% o.w.f."},
            {"name": "分散黄棕 SE-R", "dosage": 1.10, "unit": "% o.w.f."},
            {"name": "分散黑 ECO", "dosage": 0.25, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 135,
            "pH": 4.4,
            "liquor_ratio": 10,
            "dispersant": 0.6,
            "leveling_agent": 0.3,
            "hold_time": 60,
            "heating_rate": 2.0,
        },
        "machine_id": "MACHINE_14",
        "result_note": "分散剂偏低且升温过快，首次色花偏深。",
    },
    {
        "id": "hist_nylon_deep_purple_001",
        "batch_no": "HB-NYL-20260606-003",
        "fabric": "锦纶塔丝隆",
        "fiber_composition": "100%锦纶6",
        "fabric_weight_gsm": 130,
        "color_name": "深紫",
        "target_lab": {"l": 30.5, "a": 35.0, "b": -30.0},
        "actual_lab": {"l": 28.8, "a": 37.5, "b": -31.2},
        "delta_e": 2.5,
        "rft": False,
        "reworked": True,
        "dye_type": "酸性染料",
        "dye_formula": [
            {"name": "酸性红 337", "dosage": 1.40, "unit": "% o.w.f."},
            {"name": "酸性蓝 25", "dosage": 1.20, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 100,
            "pH": 4.0,
            "liquor_ratio": 10,
            "leveling_agent": 0.5,
            "acetic_acid": 1.5,
            "hold_time": 60,
            "heating_rate": 1.8,
        },
        "machine_id": "MACHINE_23",
        "result_note": "pH 偏低、升温过快，首次偏深且不匀。",
    },
    {
        "id": "hist_nylon_rose_001",
        "batch_no": "HB-NYL-20260430-002",
        "fabric": "锦纶弹力布",
        "fiber_composition": "88%锦纶 + 12%氨纶",
        "fabric_weight_gsm": 160,
        "color_name": "玫红",
        "target_lab": {"l": 48.0, "a": 51.0, "b": 2.0},
        "actual_lab": {"l": 47.5, "a": 51.8, "b": 1.4},
        "delta_e": 1.0,
        "rft": True,
        "reworked": False,
        "dye_type": "酸性染料",
        "dye_formula": [
            {"name": "酸性红 337", "dosage": 1.25, "unit": "% o.w.f."},
            {"name": "酸性蓝 25", "dosage": 0.04, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 95,
            "pH": 5.2,
            "liquor_ratio": 12,
            "leveling_agent": 1.2,
            "acetic_acid": 0.7,
            "hold_time": 40,
            "heating_rate": 1.0,
        },
        "machine_id": "MACHINE_22",
        "result_note": "弹力锦纶需控制升温，避免不匀。",
    },
    {
        "id": "hist_acrylic_royal_blue_001",
        "batch_no": "HB-ACR-20260531-003",
        "fabric": "腈纶围巾",
        "fiber_composition": "100%腈纶",
        "fabric_weight_gsm": 180,
        "color_name": "宝蓝",
        "target_lab": {"l": 30.0, "a": 8.0, "b": -42.0},
        "actual_lab": {"l": 28.5, "a": 8.8, "b": -43.2},
        "delta_e": 2.1,
        "rft": False,
        "reworked": True,
        "dye_type": "阳离子染料",
        "dye_formula": [
            {"name": "阳离子蓝 X-BL", "dosage": 1.95, "unit": "% o.w.f."},
            {"name": "阳离子红 X-GRL", "dosage": 0.08, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 100,
            "pH": 4.2,
            "liquor_ratio": 12,
            "retarder": 0.3,
            "sodium_acetate": 0.3,
            "hold_time": 60,
            "heating_rate": 1.5,
        },
        "machine_id": "MACHINE_33",
        "result_note": "缓染剂不足且升温过快，首次偏深。",
    },
    {
        "id": "hist_acrylic_violet_001",
        "batch_no": "HB-ACR-20260604-002",
        "fabric": "腈纶毛衫",
        "fiber_composition": "100%腈纶",
        "fabric_weight_gsm": 280,
        "color_name": "紫罗兰",
        "target_lab": {"l": 38.0, "a": 32.0, "b": -31.0},
        "actual_lab": {"l": 37.4, "a": 32.8, "b": -31.5},
        "delta_e": 0.9,
        "rft": True,
        "reworked": False,
        "dye_type": "阳离子染料",
        "dye_formula": [
            {"name": "阳离子红 X-GRL", "dosage": 0.88, "unit": "% o.w.f."},
            {"name": "阳离子蓝 X-BL", "dosage": 0.95, "unit": "% o.w.f."},
        ],
        "process_params": {
            "temperature": 98,
            "pH": 4.7,
            "liquor_ratio": 15,
            "retarder": 1.0,
            "sodium_acetate": 0.6,
            "hold_time": 55,
            "heating_rate": 0.7,
        },
        "machine_id": "MACHINE_32",
        "result_note": "紫罗兰批次，缓染剂充分。",
    },
]

BATCH_MATCHES = [
    {
        "id": "match_fog_blue_001",
        "intent_id": "intent_demo_fog_blue_cotton",
        "batch_id": "hist_cotton_fog_blue_001",
        "similarity_score": 0.96,
        "rank": 1,
        "difference_note": "面料、纤维组成、颜色名和目标 Lab 基本一致，克重差异在 5% 内。",
        "risk_note": "可直接作为基础方案；仍需确认本次基布白度和客户看样光源。",
        "selected": True,
    },
    {
        "id": "match_fog_blue_002",
        "intent_id": "intent_demo_fog_blue_cotton",
        "batch_id": "hist_cotton_fog_blue_002",
        "similarity_score": 0.90,
        "rank": 2,
        "difference_note": "同面料同色系，但该批次首次偏深偏蓝且发生回修。",
        "risk_note": "不要直接复用其高温和高主染料比例，可作为风险反例。",
        "selected": False,
    },
    {
        "id": "match_fog_blue_003",
        "intent_id": "intent_demo_fog_blue_cotton",
        "batch_id": "hist_cotton_sky_blue_001",
        "similarity_score": 0.72,
        "rank": 3,
        "difference_note": "同为棉活性蓝色系，但颜色更浅、更亮，织物为梭织府绸。",
        "risk_note": "只适合参考蓝相方向，不适合直接复用染料用量。",
        "selected": False,
    },
    {
        "id": "match_poly_black_001",
        "intent_id": "intent_demo_polyester_black",
        "batch_id": "hist_polyester_black_001",
        "similarity_score": 0.97,
        "rank": 1,
        "difference_note": "面料、颜色和染料体系完全匹配，实际 Delta E 为 1.0。",
        "risk_note": "可作为基础方案；需注意氨纶混纺温度上限。",
        "selected": True,
    },
    {
        "id": "match_poly_black_002",
        "intent_id": "intent_demo_polyester_black",
        "batch_id": "hist_polyester_ink_green_001",
        "similarity_score": 0.55,
        "rank": 2,
        "difference_note": "同为涤纶中深色，但该批次有升温过快和色花回修记录。",
        "risk_note": "用于提示分散染料升温速率和分散剂不足风险。",
        "selected": False,
    },
    {
        "id": "match_nylon_purple_001",
        "intent_id": "intent_demo_nylon_purple",
        "batch_id": "hist_nylon_deep_purple_001",
        "similarity_score": 0.95,
        "rank": 1,
        "difference_note": "面料、颜色、染料体系完全匹配，但历史结果为回修批次。",
        "risk_note": "这是关键风险样本：pH 偏低、升温过快、匀染剂不足会导致偏深不匀。",
        "selected": True,
    },
    {
        "id": "match_nylon_purple_002",
        "intent_id": "intent_demo_nylon_purple",
        "batch_id": "hist_nylon_rose_001",
        "similarity_score": 0.62,
        "rank": 2,
        "difference_note": "同为锦纶酸性体系，红相接近，但不是紫色目标。",
        "risk_note": "可参考 95°C、pH5.2、慢升温的安全窗口。",
        "selected": False,
    },
    {
        "id": "match_acrylic_blue_001",
        "intent_id": "intent_demo_acrylic_royal_blue",
        "batch_id": "hist_acrylic_royal_blue_001",
        "similarity_score": 0.96,
        "rank": 1,
        "difference_note": "面料、颜色、染料体系完全匹配，但历史批次发生回修。",
        "risk_note": "关键风险样本：缓染剂不足和升温过快导致偏深色花。",
        "selected": True,
    },
    {
        "id": "match_acrylic_blue_002",
        "intent_id": "intent_demo_acrylic_royal_blue",
        "batch_id": "hist_acrylic_violet_001",
        "similarity_score": 0.64,
        "rank": 2,
        "difference_note": "同为腈纶阳离子体系，蓝相参与较多，但红相更高。",
        "risk_note": "可参考缓染剂 1.0g/L 和 0.7°C/min 慢升温策略。",
        "selected": False,
    },
    {
        "id": "match_acrylic_blue_003",
        "intent_id": "intent_demo_acrylic_royal_blue",
        "batch_id": "hist_polyester_royal_blue_001",
        "similarity_score": 0.42,
        "rank": 3,
        "difference_note": "颜色同为宝蓝，但涤纶分散体系和腈纶阳离子体系不同。",
        "risk_note": "不可复用配方和工艺，只作为颜色方向参考。",
        "selected": False,
    },
]
